[mcp_servers.railway]
command = "npx"
args = [
    "-y",
    "@railway/mcp-server",
]

[mcp_servers.resend]
command = "npx"
args = [
    "-y",
    "resend-mcp",
]

[mcp_servers.resend.env]
RESEND_API_KEY = "re_bQqpGTxn_7GZx24PgH5mzwyDHLZS1My28"
